import esbuild from 'esbuild'
import process from 'process'
import builtins from 'builtin-modules'
import { copyFileSync, rmSync, mkdirSync, existsSync } from 'fs'

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`

const prod = process.argv[2] === 'production'
const deploy = process.argv[2] === 'deploy'
const OBSIDIAN_PLUGIN_PATH = 'G:/My Drive/Nexus/.obsidian/plugins/lachesis'

// Clean and prepare dist folder
rmSync('dist', { recursive: true, force: true })
mkdirSync('dist', { recursive: true })

// Copy static assets to dist
copyFileSync('manifest.json', 'dist/manifest.json')
copyFileSync('styles.css', 'dist/styles.css')

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtins,
  ],
  format: 'cjs',
  target: 'es2018',
  logLevel: 'info',
  sourcemap: (prod || deploy) ? false : 'inline',
  treeShaking: true,
  outfile: 'dist/main.js',
})

if (prod || deploy) {
  await context.rebuild()

  if (deploy) {
    if (!existsSync(OBSIDIAN_PLUGIN_PATH)) {
      mkdirSync(OBSIDIAN_PLUGIN_PATH, { recursive: true })
    }
    copyFileSync('dist/main.js', `${OBSIDIAN_PLUGIN_PATH}/main.js`)
    copyFileSync('dist/manifest.json', `${OBSIDIAN_PLUGIN_PATH}/manifest.json`)
    copyFileSync('dist/styles.css', `${OBSIDIAN_PLUGIN_PATH}/styles.css`)
    console.log(`\n✓ Deployed to ${OBSIDIAN_PLUGIN_PATH}`)
  }

  process.exit(0)
} else {
  await context.watch()
}
