import esbuild from 'esbuild'
import process from 'process'
import builtins from 'builtin-modules'
import { copyFileSync, rmSync, mkdirSync, existsSync, cpSync } from 'fs'
import { config } from 'dotenv'
import { join, resolve } from 'path'
import { homedir } from 'os'

// Load .env file
config()

// Expand ~ to home directory (Node.js doesn't do this automatically)
function expandHome(path) {
  if (!path) return path
  if (path.startsWith('~/')) {
    return join(homedir(), path.slice(2))
  }
  return path
}

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`

const prod = process.argv[2] === 'production'
const OBSIDIAN_PLUGIN_PATH = expandHome(process.env.OBSIDIAN_PLUGIN_PATH)
const PROJECT_PATH = expandHome(process.env.PROJECT_PATH)

// Path to Claude Agent SDK files
const CLAUDE_SDK_PATH = resolve('node_modules/@anthropic-ai/claude-agent-sdk')

// Clean and prepare dist folder
rmSync('dist', { recursive: true, force: true })
mkdirSync('dist', { recursive: true })

// Copy static assets to dist
copyFileSync('manifest.json', 'dist/manifest.json')

// Copy Claude Agent SDK cli.js and dependencies to dist
copyFileSync(join(CLAUDE_SDK_PATH, 'cli.js'), 'dist/cli.js')
copyFileSync(join(CLAUDE_SDK_PATH, 'resvg.wasm'), 'dist/resvg.wasm')
copyFileSync(join(CLAUDE_SDK_PATH, 'tree-sitter.wasm'), 'dist/tree-sitter.wasm')
copyFileSync(join(CLAUDE_SDK_PATH, 'tree-sitter-bash.wasm'), 'dist/tree-sitter-bash.wasm')
if (existsSync(join(CLAUDE_SDK_PATH, 'vendor'))) {
  cpSync(join(CLAUDE_SDK_PATH, 'vendor'), 'dist/vendor', { recursive: true })
}

// Bundle CSS from modular source files
await esbuild.build({
  entryPoints: ['src/styles/index.css'],
  bundle: true,
  outfile: 'dist/styles.css',
  logLevel: 'info',
})

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...builtins,
  ],
  define: {
    'process.env.PROJECT_PATH': PROJECT_PATH ? JSON.stringify(PROJECT_PATH) : 'undefined',
    'process.env.CLAUDE_CLI_PATH': OBSIDIAN_PLUGIN_PATH ? JSON.stringify(join(OBSIDIAN_PLUGIN_PATH, 'cli.js')) : 'undefined',
  },
  format: 'cjs',
  target: 'es2018',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'dist/main.js',
})

if (prod) {
  await context.rebuild()

  if (OBSIDIAN_PLUGIN_PATH) {
    if (!existsSync(OBSIDIAN_PLUGIN_PATH)) {
      mkdirSync(OBSIDIAN_PLUGIN_PATH, { recursive: true })
    }
    copyFileSync('dist/main.js', `${OBSIDIAN_PLUGIN_PATH}/main.js`)
    copyFileSync('dist/manifest.json', `${OBSIDIAN_PLUGIN_PATH}/manifest.json`)
    copyFileSync('dist/styles.css', `${OBSIDIAN_PLUGIN_PATH}/styles.css`)
    // Copy Claude Agent SDK files
    copyFileSync('dist/cli.js', `${OBSIDIAN_PLUGIN_PATH}/cli.js`)
    copyFileSync('dist/resvg.wasm', `${OBSIDIAN_PLUGIN_PATH}/resvg.wasm`)
    copyFileSync('dist/tree-sitter.wasm', `${OBSIDIAN_PLUGIN_PATH}/tree-sitter.wasm`)
    copyFileSync('dist/tree-sitter-bash.wasm', `${OBSIDIAN_PLUGIN_PATH}/tree-sitter-bash.wasm`)
    if (existsSync('dist/vendor')) {
      cpSync('dist/vendor', `${OBSIDIAN_PLUGIN_PATH}/vendor`, { recursive: true })
    }
    console.log(`\n✓ Deployed to ${OBSIDIAN_PLUGIN_PATH}`)
  }

  process.exit(0)
} else {
  await context.watch()
}
