/**
 * GROOM TASKS: Review and process existing potential tasks from log.
 * Non-AI workflow - directly parses Log.md and opens review modal.
 */

import type { WorkflowDefinition } from '../types'
import { PROJECT_FILES } from './constants'

export const groomTasksWorkflow: WorkflowDefinition = {
  name: 'groom-tasks',
  displayName: 'Log: Groom Tasks',
  description: 'Review and process existing potential tasks from log',
  intent:
    'Parse Log.md for existing AI-generated potential tasks blocks and open a review modal ' +
    'to Keep, Reject, or Move tasks to Tasks.md. This workflow does NOT generate new tasks - ' +
    'it only processes tasks that were previously generated by the Generate Tasks workflow.',
  readFiles: [PROJECT_FILES.log, PROJECT_FILES.tasks],
  writeFiles: [PROJECT_FILES.log, PROJECT_FILES.tasks],
  risk: 'low',
  confirmation: 'preview',
  allowsDelete: false,
  allowsCrossFileMove: true,
  rules: [
    'Parse Log.md for <!-- AI: potential-tasks --> blocks',
    'Show all actionable (non-strikethrough, unchecked) tasks in a review modal',
    'Allow user to Keep, Reject, or Move each task',
    'Keep: Leave task in Log.md as-is',
    'Reject: Apply strikethrough to task text in Log.md',
    'Move to Current: Remove task from Log.md, add to "Current" section in Tasks.md',
    'Remove empty potential-tasks blocks after processing',
  ],
  usesAI: false,
  hidden: true,
}
