// Prompts/PROMPTS-README.md template
import type { ProjectDefinition } from '../../core/project/types.ts'

export function generatePromptsReadme(project: ProjectDefinition): string {
  return `# Prompts for ${project.name}

This folder is for **Claude / AI / advisor prompts** used with this project.

## Recommended contents

- System prompts for each advisor defined in \`../Advisors.json\`
- Project-specific instructions for coding agents
- Any "core context" files you want to copy/paste into tools

> When you create a code project (Tauri app, Next.js app, etc.),
> copy/paste the relevant prompts from here into that repo so your tools
> understand the project from day one.

## Suggested structure

\`\`\`
Prompts/
├── PROMPTS-README.md (this file)
├── advisors/          # Per-advisor prompt files
│   ├── architect.md
│   ├── strategist.md
│   └── ...
├── tools/             # Prompts for IDEs, agents, etc.
│   ├── cursor.md
│   ├── claude-code.md
│   └── ...
└── global.md          # Shared context for all agents
\`\`\`

## Getting Started

1. Create \`global.md\` with core project context
2. Add advisor-specific prompts as you define their personalities
3. When you start coding, copy relevant prompts to your code repo

---

*Generated by Lachesis on ${new Date().toISOString().split('T')[0]}*
`
}
